---
# file: tasks/config.yml

- name: config - add docker storage setup
  lineinfile: dest="{{docker_init_config_directory}}/{{docker_package}}-storage-setup" state="present" line="STORAGE_DRIVER=\"\""
  when: docker_package|length > 0
  become: yes

- name: config - setup docker mtu on Openstack VMs
  lineinfile: dest="{{docker_init_config_directory}}/{{docker_package}}" state="present" backrefs=true regexp='^{{docker_opts}}=(?:\'|\")?((?:\s*[\w=\/\-\.](?<!--mtu=1450)\s*)*)(?:\'|\")?$' line='{{docker_opts}}="\1 --mtu=1450"'
  when: docker_package|length > 0 and ansible_product_name == "OpenStack Nova"
  become: yes

