---
# file: tasks/main.yml

- include: vars.yml
  tags:
    - vars

- include: check.yml
  tags:
    - check

- include: package.yml
  tags:
    - package

- include: service.yml
  tags:
    - service
