---
# file: tasks/package.yml

- name: package - remove unwanted packages
  package: name="{{item}}" state=absent
  with_items: "{{docker_package_purge}}"
  when: docker_package_purge|length > 0
  become: yes

- name: package - add package dependencies
  package: name="{{item}}" state=present
  with_items: "{{docker_package_dependencies}}"
  when: docker_package_dependencies|length > 0
  become: yes

- name: package - add docker package
  package: name="{{item}}" state=present
  with_items: "{{docker_package}}"
  when: docker_package|length > 0
  become: yes
