---
# file: tasks/package.yml

- name: package - remove unwanted packages
  package: name="{{item}}" state=absent
  with_items: "{{docker_package_unwanted}}"
  when: docker_package_unwanted|length > 0
  become: yes

- name: package - add package dependencies
  package: name="{{item}}" state=present
  with_items: "{{docker_package_dependencies}}"
  when: docker_package_dependencies|length > 0
  become: yes

- name: package - add docker package
  package: name="{{item}}" state=present
  with_items: "{{docker_package}}"
  when: docker_package|length > 0

- name: package - add docker storage setup
  lineinfile: dest="/etc/sysconfig/{{item}}-storage-setup" state="present" line="STORAGE_DRIVER=\"\""
  with_items: "{{docker_package}}"
  when: docker_package|length > 0
  become: yes
