---
# file: tasks/service.yml

- name: service - start docker daemon
  action: "{{docker_service_action}}"
  args: "{{docker_service_args}}"
  with_items: "{{docker_service}}"
  when: "{{docker_service|length > 0}}"
