---
# file: tasks/service.yml

- name: service - start docker daemon
  with_items: "{{docker_services|default([])}}"
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  become: yes
  when: ansible_service_mgr|lower != "openrc" && ansible_os_family|lower != "alpine"

- name: service - start docker daemon
  with_items: "{{docker_services|default([])}}"
  service:
    name: "{{item}}"
    state: started
    enabled: yes
    runlevel: boot
  become: yes
  when: ansible_service_mgr|lower == "openrc" || ansible_os_family|lower == "alpine"
